### ISSUE TITLE
コード改善提案（numpy averageの使用）

### ISSUE THREAD

**Issue by twtwtw-gj** [puppoppo/location_tool#5]
https://github.com/puppoppo/location_tool/blob/5ded04e415323e6653e15617e30a824abbdabefc/AAgraph.py#L119-L122

これはvalueの平均を取っているの？（そもそもvalueが20まであるかどうか知らないけど）
だったらnumpyのaverage()でよくない？

**Comment by puppoppo** [comment]
そうかも
というかXとかNAの扱いについて悩みはじめたからまた変えるかも
